apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-COLOR
  labels:
    app: myapp
    color: COLOR
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      color: COLOR
  template:
    metadata:
      labels:
        app: myapp
        color: COLOR
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
